#pragma once

#include <sdkconfig.h>

#define CHIP_CRYPTO_MBEDTLS 1
#define CHIP_CRYPTO_PSA 0
#define CHIP_CRYPTO_PSA_SPAKE2P 0
#define CHIP_CRYPTO_PSA_AEAD_SINGLE_PART 0
#define CHIP_CRYPTO_KEYSTORE_PSA 0
#define CHIP_CRYPTO_KEYSTORE_RAW 1
#define CHIP_CRYPTO_KEYSTORE_APP 0
#define CHIP_CRYPTO_OPENSSL 0
#define CHIP_CRYPTO_BORINGSSL 0
#define CHIP_CRYPTO_PLATFORM 0
#define CHIP_CRYPTO_TRUSTY_OS 0
